services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile

    container_name: devops-app

    ports:
      - "3000:3000"

    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts

    container_name: jenkins

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home

    restart: unless-stopped

volumes:
  jenkins_home: